### PR TITLE
Stop GT++ editing grave hardness

### PR DESCRIPTION
**Pull request by Connor-Colenso**
GT++ sets the hardness to 6, so that hungry nodes can't eat graves. Lets move it to the actual mod.

Also spotless + buildscript update.

### CODE REVIEW

**Comment by Alexdoru** [comment]
Can you squash the buildscript update and the spotless into one commit and then force push it so that we can merge it with rebase and it will only show 2 commits on the main branch

**Comment by Alexdoru** [comment]
And also is there a linked PR to remove that feature from GT++?

**Comment by Connor-Colenso** [comment]
> And also is there a linked PR to remove that feature from GT++?

Not yet, this can still be merged now though, no harm in it.

**Comment by Alexdoru** [comment]
Can you squash your two lasts commits and force push please

**Review by Alexdoru — APPROVED** [review]

**Pull request merged**
